// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/19/2026, 8:49:44 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/alexis/Documents/Magdata/Liga/liga-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/plugins/**/*.{js,ts,mjs}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/composables/**/*.{js,ts,mjs}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/utils/**/*.{js,ts,mjs}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/alexis/Documents/Magdata/Liga/liga-frontend/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;